(function timelineApp(global) {
  const stateApi = global.MembarTimelineState;
  const handoff = global.MembarTimelineHandoff;
  const moments = [
    { id: 'first-hum', date: '10 Jul', fullDate: '10 Jul 2026', title: 'A first quiet hum', line: 'A fragment is small enough to keep listening to.', status: 'canonical · seed', version: 'v01', change: 'needs-review', accent: '#8fccc0', hue: 174, source: 'Sea Glass · Verse · 00:12.4 · Am', context: { song: 'Sea Glass', artist: 'Mara Vale', source: 'sea-glass_take-03.m4a', section: 'Verse', time: '00:12.4', seconds: 12.4, chord: 'Am', bars: '4 bars', lyric: 'The sea keeps a little light', provenance: 'performed source · synthetic fixture' }, edges: ['Live Session', 'Memory Archive'], route: 'archive/2026-07-31-universe-v1/source-video-workbench.html' },
    { id: 'quiet-cue', date: '12 Jul', fullDate: '12 Jul 2026', title: 'Cue as a quiet section', line: 'One useful word arrives without interrupting the take.', status: 'canonical · live', version: 'v03', change: 'stable', accent: '#e5a17f', hue: 12, source: 'Sea Glass · Verse · 00:24.8 · Am', context: { song: 'Sea Glass', artist: 'Mara Vale', source: 'sea-glass_take-03.m4a', section: 'Verse', time: '00:24.8', seconds: 24.8, chord: 'Am', bars: '4 bars', lyric: 'Leave the window open', provenance: 'performed source · synthetic fixture' }, edges: ['Rhyme Compass', 'Structure Lens'], route: 'archive/2026-07-31-universe-v1/source-video-workbench.html' },
    { id: 'source-frame', date: '23 Jul', fullDate: '23 Jul 2026', title: 'Source stays in frame', line: 'The lyric, chord, section, and source frame move as one.', status: 'cue bridge', version: 'v03', change: 'updated', accent: '#d8bd73', hue: 42, source: 'North Window · Pre-chorus · 00:47.3 · Em', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Pre-chorus', time: '00:47.3', seconds: 47.3, chord: 'Em', bars: '8 bars', lyric: 'I left a light on for the weather', provenance: 'performed source · synthetic fixture' }, edges: ['Source Workbench', 'Structure Lens', 'Live Session'], route: 'archive/2026-07-31-universe-v1/source-video-workbench.html' },
    { id: 'direct-scrub', date: '24 Jul', fullDate: '24 Jul 2026', title: 'Direct source scrub', line: 'A remembered word has a place you can return to.', status: 'exact retrieval', version: 'v04', change: 'new', accent: '#91d0bc', hue: 157, source: 'North Window · Verse · 00:47.3 · Em', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Verse', time: '00:47.3', seconds: 47.3, chord: 'Em', bars: '8 bars', lyric: 'We are the weather in the room', provenance: 'performed source · synthetic fixture' }, edges: ['Memory Archive', 'Source Workbench'], route: 'archive/2026-07-31-universe-v1/source-video-workbench.html' },
    { id: 'constellation', date: '31 Jul', fullDate: '31 Jul 2026', title: 'Audio-visual constellation', line: 'A source moment becomes a visual world without replacing the take.', status: 'orbit study', version: 'v01', change: 'new', accent: '#a9a0ed', hue: 252, source: 'North Window · Chorus · 01:00.0 · G', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Chorus', time: '01:00.0', seconds: 60, chord: 'G', bars: '8 bars', lyric: 'We are the weather in the room', provenance: 'performed source · synthetic fixture' }, edges: ['Six visual worlds', 'Memory Archive', 'Direct source scrub'], route: 'archive/2026-07-31-universe-v1/artboard-constellation.html' },
    { id: 'live-rehearsal', date: '05 Aug', fullDate: '05 Aug 2026', title: 'Live rehearsal continuity', line: 'A kept source moment becomes two ways back into the song.', status: 'continuity study', version: 'v01', change: 'new', accent: '#e5a17f', hue: 16, source: 'North Window · Chorus · 01:00.0 · G', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Chorus', time: '01:00.0', seconds: 60, chord: 'G', bars: '8 bars', lyric: 'We are the weather in the room', provenance: 'performed source · synthetic fixture' }, edges: ['Live Session', 'Source Workbench', 'Song Workbench', 'Memory Archive'], route: 'archive/2026-07-31-universe-v1/live-session-continuity.html' },
    { id: 'timeline', date: '10 Aug', fullDate: '10 Aug 2026', title: 'Timeline evolution', line: 'Time itself becomes the way to understand a changing idea.', status: 'active study', version: 'v01', change: 'new', accent: '#d8bd73', hue: 43, source: 'North Window · Bridge · 01:14.2 · Am', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Bridge', time: '01:14.2', seconds: 74.2, chord: 'Am', bars: '8 bars', lyric: 'The room keeps turning blue', provenance: 'performed source · synthetic fixture' }, edges: ['Live rehearsal continuity', 'Memory Archive', 'Home'], route: 'archive/2026-07-31-universe-v1/live-session-continuity.html' },
    { id: 'return', date: 'now', fullDate: '10 Aug 2026', title: 'A moment worth reopening', line: 'Hold the thread. Leave the lab. Come back exactly here.', status: 'selected study', version: 'v01', change: 'updated', accent: '#8fccc0', hue: 174, source: 'North Window · Chorus · 01:00.0 · G', context: { song: 'North Window', artist: 'Jo Sable', source: 'north-window_take-02.mp4', section: 'Chorus', time: '01:00.0', seconds: 60, chord: 'G', bars: '8 bars', lyric: 'We are the weather in the room', provenance: 'performed source · synthetic fixture' }, edges: ['Timeline evolution', 'Source Workbench', 'Memory Archive'], route: 'archive/2026-07-31-universe-v1/live-session-continuity.html' },
  ].map((moment, index) => ({ ...moment, index, last_touched: moment.fullDate }));

  const $ = (id) => document.getElementById(id);
  const root = $('world'); const scrubber = $('scrubber'); const momentList = $('momentList'); const detail = $('momentDetail');
  let state = { index: 5, playing: false, heldId: null }; let timer = null; let activeFilter = 'all';

  function load() { try { const raw = JSON.parse(localStorage.getItem(stateApi.STORAGE_KEY)); state = raw ? stateApi.restore(raw, moments.length) : { ...stateApi.restore(null, moments.length), index: 5 }; } catch { state = { ...stateApi.restore(null, moments.length), index: 5 }; } const returnId = new URLSearchParams(global.location.search).get('returnMoment'); const returnedIndex = moments.findIndex((moment) => moment.id === returnId); if (returnedIndex >= 0) { state = { ...state, index: returnedIndex, heldId: returnId }; save(); } }
  function save() { localStorage.setItem(stateApi.STORAGE_KEY, JSON.stringify({ index: state.index, heldId: state.heldId })); }
  function visibleMoments() { return moments.filter((moment) => activeFilter === 'all' || moment.change === activeFilter); }
  function renderWorld(moment) {
    root.dataset.world = moment.id; root.style.setProperty('--hue', moment.hue); root.style.setProperty('--world-accent', moment.accent); root.style.setProperty('--glow', `${moment.accent}88`);
    $('worldDate').textContent = moment.fullDate; $('worldStatus').textContent = `${moment.change.toUpperCase()} · ${moment.status}`; $('worldTitle').textContent = moment.title; $('worldLine').textContent = moment.line; $('worldSource').textContent = moment.source; $('worldIndex').textContent = `${String(moment.index + 1).padStart(2, '0')} / ${String(moments.length).padStart(2, '0')}`;
    scrubber.value = moment.index; document.querySelectorAll('.scrub-ticks i').forEach((tick) => tick.classList.toggle('is-active', Number(tick.dataset.index) === moment.index));
  }
  function renderList() { const visible = visibleMoments(); momentList.innerHTML = visible.map((moment) => `<button class="moment-item${moment.index === state.index ? ' is-selected' : ''}" style="--accent:${moment.accent}" data-index="${moment.index}" type="button"><span class="moment-date">${moment.date}</span><span class="moment-dot" aria-hidden="true"></span><span class="moment-copy"><strong>${moment.title}</strong><small>${moment.status} · ${moment.version}</small></span><span class="moment-change">${moment.change}</span></button>`).join(''); momentList.querySelectorAll('[data-index]').forEach((button) => button.addEventListener('click', () => select(Number(button.dataset.index)))); }
  function renderDetail(moment) { const held = state.heldId === moment.id; detail.innerHTML = `<div class="detail-top"><span>${moment.last_touched} · ${moment.version}</span><span class="detail-change" style="color:${moment.accent}">${moment.change}</span></div><h3>${moment.title}</h3><p class="detail-hypothesis">${moment.line}</p><div class="detail-meta"><span><small>status</small><strong>${moment.status}</strong></span><span><small>nodes</small><strong>103 preserved</strong></span><span><small>source</small><strong>synthetic</strong></span></div><div class="edges">${moment.edges.map((edge) => `<span class="edge">↗ ${edge}</span>`).join('')}</div><a class="reopen" href="${handoff.routeHref(moment.route, moment)}">Reopen archived study <span>↗</span></a>${held ? '<p class="held-note">● held locally · this moment will be here after reload</p>' : ''}`; }
  function render() { const moment = moments[state.index]; renderWorld(moment); renderList(); renderDetail(moment); $('playButton').setAttribute('aria-pressed', String(state.playing)); $('playLabel').textContent = state.playing ? 'Pause evolution' : 'Play evolution'; $('playButton').querySelector('.play-icon').textContent = state.playing ? 'Ⅱ' : '▶'; $('transportState').textContent = state.playing ? 'World is evolving · tap pause to stay' : state.heldId === moment.id ? 'Held moment restored' : 'Ready to scrub'; $('holdButton').textContent = state.heldId === moment.id ? 'Release this hold' : 'Hold this moment'; }
  function select(index) { state = { ...state, index: stateApi.clampIndex(index, moments.length) }; render(); }
  function togglePlay() { state = stateApi.togglePlaying(state); if (state.playing) { timer = window.setInterval(() => select((state.index + 1) % moments.length), 1200); } else { window.clearInterval(timer); timer = null; } render(); }
  function hold() { state = state.heldId === moments[state.index].id ? { ...state, heldId: null } : stateApi.holdMoment(state, moments); save(); render(); }
  load(); $('scrubTicks').innerHTML = moments.map((moment) => `<i data-index="${moment.index}" class="${moment.index === state.index ? 'is-active' : ''}"></i>`).join(''); scrubber.addEventListener('input', (event) => select(Number(event.target.value))); $('playButton').addEventListener('click', togglePlay); $('holdButton').addEventListener('click', hold);
  document.querySelectorAll('.filter').forEach((button) => button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('.filter').forEach((item) => item.classList.toggle('is-active', item === button)); renderList(); }));
  $('motionToggle').addEventListener('change', (event) => { document.body.classList.toggle('reduce-motion', event.target.checked); });
  render();
  global.MembarTimeline = Object.freeze({ moments, getState: () => ({ ...state }), select, hold });
})(window);
